"""sparse-layers: structured sparse layers for building memory-efficient neural networks."""

from sparse_layers.layers import (
    ButterflyLinear,
    ButterflyMLP,
    ButterflyMultiHeadAttention,
    CustomLinear,
    CustomMLP,
    MultiHeadAttention,
    PaddedButterflyLinear,
    SimpleMLP,
)
from sparse_layers.sse import (
    LinearAttention,
    LinearAttentionConfig,
    NaiveMultiPartitionState,
    NaiveSSEAttention,
    NaiveSSEMultiHeadAttention,
    SSEAttention,
    SSEAttentionAdaptive,
    SSEAttentionAdaptiveConfig,
    SSEAttentionConfig,
    SSEMaskingOps,
    SSEMaskingOpsConfig,
    SSEMultiHeadAttention,
    SSEMultiHeadAttentionConfig,
    SSEMultiPartitionState,
    SSEMultiPartitionStateConfig,
    SSEPartitionSelector,
    SSEPartitionSelectorConfig,
    SSESparseSoftmax,
    SSESparseSoftmaxConfig,
    SSEVarlenOps,
    SSEVarlenOpsConfig,
)

__all__ = [
    # Layers
    "ButterflyLinear",
    "ButterflyMLP",
    "ButterflyMultiHeadAttention",
    "CustomLinear",
    "CustomMLP",
    "MultiHeadAttention",
    "PaddedButterflyLinear",
    "SimpleMLP",
    # SSE
    "LinearAttention",
    "LinearAttentionConfig",
    "NaiveMultiPartitionState",
    "NaiveSSEAttention",
    "NaiveSSEMultiHeadAttention",
    "SSEAttention",
    "SSEAttentionAdaptive",
    "SSEAttentionAdaptiveConfig",
    "SSEAttentionConfig",
    "SSEMaskingOps",
    "SSEMaskingOpsConfig",
    "SSEMultiHeadAttention",
    "SSEMultiHeadAttentionConfig",
    "SSEMultiPartitionState",
    "SSEMultiPartitionStateConfig",
    "SSEPartitionSelector",
    "SSEPartitionSelectorConfig",
    "SSESparseSoftmax",
    "SSESparseSoftmaxConfig",
    "SSEVarlenOps",
    "SSEVarlenOpsConfig",
]
